jingo.declare(
{
    require: 
    [
        "shared.model.ProgramBrief"
    ],
    name: 'shared.model.local.LocalRecommendationsProxy',
    as: function() 
    {

        shared.model.RecommendationsProxy = function()
        {
            puremvc.Proxy.apply(this, [shared.model.RecommendationsProxy.NAME, new Array()]);
        }

        shared.model.RecommendationsProxy.prototype = new puremvc.Proxy;
        shared.model.RecommendationsProxy.prototype.parent = puremvc.Proxy.prototype;
        shared.model.RecommendationsProxy.prototype.constructor = shared.model.RecommendationsProxy;
        
        shared.model.RecommendationsProxy.NAME = "RecommendationsProxy";

        shared.model.RecommendationsProxy.prototype.getRecommendations = function(userId, contextId, successCallback, failCallback)
        {
            if (DEVICE_MODE_ENABLED)
            {
                window.plugins.ApplicationPreferences.getAsBoolean(
                    'override_video', 
                    Relegate.create(this, this._getRecommendationsInternal, userId, contextId, successCallback, failCallback),
                    Relegate.create(
                        this,
                        function() 
                        {
                            console.log('Unable to get override video value.  Make sure the value is set in the Settings application.');
                            this._getRecommendationsInternal(OVERRIDE_CONTENT_VIDEO, userId, contextId, successCallback, failCallback);
                        }, 
                        this));
            }
            else
            {  
                this._getRecommendationsInternal(OVERRIDE_CONTENT_VIDEO, userId, contextId, successCallback, failCallback);
            }
        }
        
        shared.model.RecommendationsProxy.prototype._getRecommendationsInternal = function(overrideVideo, userId, contextId, successCallback, failCallback)
        {
            //TODO:  for now just a hacked hardcoded data representation for now of recommended shows.
            var testData = new Array();

            if (contextId == "orderedApp")
            {
                // First set of 10
                testData.push(new shared.model.ProgramBrief(111,'The Lion King', shared.model.ProgramBrief.MOVIE, 'http://10.6.10.157/~ux_design02/images/wizardsOfWaverlyPlace2M-bad.png', 'http://10.6.10.157/~ux_design02/images/wizardsOfWaverlyPlace2M-bad.png', 'http://10.6.10.157/~ux_design02/images/wizardsOfWaverlyPlace2M-bad.png', 'images/pages/test/medMainImgTest_279x163.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(222,'Sesame Street', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(333,'Mickey Mouse Club', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(444,'Show Title 4', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(555,'Show Title 5', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(666,'Show Title 6', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(777,'Show Title 7', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(888,'Show Title 8', shared.model.ProgramBrief.MOVIE, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(999,'Show Title 9', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1010,'Show Title 10', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
        
                // Second set of 10
                testData.push(new shared.model.ProgramBrief(1111,'Show Title 11', shared.model.ProgramBrief.MOVIE, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1212,'Show Title 12', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1313,'Show Title 13', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1414,'Show Title 14', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1515,'Show Title 15', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1616,'Show Title 16', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1717,'Show Title 17', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1818,'Show Title 18', shared.model.ProgramBrief.MOVIE, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1919,'Show Title 19', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2020,'Show Title 20', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
        
                // Third set of 10
                testData.push(new shared.model.ProgramBrief(2121,'Show Title 21', shared.model.ProgramBrief.MOVIE, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2222,'Show Title 22', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2323,'Show Title 23', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2424,'Show Title 24', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2525,'Show Title 25', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2626,'Show Title 26', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2727,'Show Title 27', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2828,'Show Title 28', shared.model.ProgramBrief.MOVIE, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2929,'Show Title 29', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(3030,'Show Title 30', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
            }
            else if (contextId == "randomApp")
            {
                // First set of 9
                testData.push(new shared.model.ProgramBrief(111,'Show Title 8', shared.model.ProgramBrief.MOVIE, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(222,'The Lion King', shared.model.ProgramBrief.MOVIE, 'http://10.6.10.157/~ux_design02/images/wizardsOfWaverlyPlace2M-bad.png', 'http://10.6.10.157/~ux_design02/images/wizardsOfWaverlyPlace2M-bad.png', 'http://10.6.10.157/~ux_design02/images/wizardsOfWaverlyPlace2M-bad.png', 'images/pages/test/medMainImgTest_279x163.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(333,'Sesame Street', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(444,'Sesame Street', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(555,'Sesame Street', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(666,'Show Title 6', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(777,'Sesame Street', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(888,'Show Title 7', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(999,'Sesame Street', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                
                // Remaining tiles left in queue
                testData.push(new shared.model.ProgramBrief(1010,'Show Title 10', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1111,'Show Title 11', shared.model.ProgramBrief.MOVIE, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1212,'Show Title 12', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1313,'Show Title 13', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1414,'Show Title 14', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1515,'Show Title 15', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1616,'Show Title 16', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1717,'Show Title 17', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1818,'Show Title 18', shared.model.ProgramBrief.MOVIE, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(1919,'Show Title 19', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2020,'Show Title 20', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2121,'Show Title 21', shared.model.ProgramBrief.MOVIE, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2222,'Show Title 22', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2323,'Show Title 23', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2424,'Show Title 24', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2525,'Show Title 25', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2626,'Show Title 26', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2727,'Show Title 27', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2828,'Show Title 28', shared.model.ProgramBrief.MOVIE, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(2929,'Show Title 29', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
                testData.push(new shared.model.ProgramBrief(3030,'Show Title 30', shared.model.ProgramBrief.TVSERIES, 'images/pages/test/mainImageTest_400x240.png', 'images/pages/test/medMainImgTest_279x163.png', 'images/pages/test/smMainImageTest_190x111.png', 'images/pages/test/mainImageTest_400x240.png', this._determineVideoURL(overrideVideo, "http://www.html5doctor.com/demos/video-canvas-magic/video.mp4")));
            }
            successCallback(testData);
        }
        
        shared.model.RecommendationsProxy.prototype._determineVideoURL = function(overrideVideo, videoURL)
        {
            return (overrideVideo) ? OVERRIDE_CONTENT_VIDEO_URL : videoURL;
        }
        
    }
});
